// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "img_path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
	}
	// DocumentPostsColumns holds the columns for the "document_posts" table.
	DocumentPostsColumns = []*schema.Column{
		{Name: "document_id", Type: field.TypeInt},
		{Name: "post_id", Type: field.TypeInt},
	}
	// DocumentPostsTable holds the schema information for the "document_posts" table.
	DocumentPostsTable = &schema.Table{
		Name:       "document_posts",
		Columns:    DocumentPostsColumns,
		PrimaryKey: []*schema.Column{DocumentPostsColumns[0], DocumentPostsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_posts_document_id",
				Columns:    []*schema.Column{DocumentPostsColumns[0]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "document_posts_post_id",
				Columns:    []*schema.Column{DocumentPostsColumns[1]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocumentsTable,
		PostsTable,
		DocumentPostsTable,
	}
)

func init() {
	DocumentPostsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentPostsTable.ForeignKeys[1].RefTable = PostsTable
}
